#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#!/bin/bash
SRC_PATTERN="CHANGELOG.md"
RED='\033[0;31m'
NC='\033[0m'

if ! git diff --name-only HEAD origin/develop | grep --quiet "$SRC_PATTERN"
then
  printf "\n ${RED}Acho que faltou atualizar o ${SRC_PATTERN}, da uma olhada pra nós!${NC} \n\n "
  exit 0
fi

if ! git diff HEAD --quiet
then 
  printf "\n\n ${RED}As alterações locais não estão todas comitadas. Para garantir que os testes rodem com segurança, a branch local precisa estar em conformidade com a HEAD. ${NC}\n\n"
else
  yarn test
fi

code_files_count=`git --no-pager diff --name-only --cached | grep -E "packages\/(?:package1|package2)\/.+\.(?:js|ts|html)$" | wc -l`

if [ $code_files_count == 0 ]
then
    printf "\n\n Nenhum arquivo de codigo foi editado, não precisamos rodar os testes! \n\n"
    exit 0
fi